#!/bin/bash
#SBATCH --qos=jgi_exvivo
#SBATCH --time=10:00:00
#SBATCH --nodes=1
#SBATCH --account=plant
#SBATCH --job-name=vcf2hapmap
#SBATCH --output=vcf2hapmap.out
#SBATCH --error=vcf2hapmap.err

perl /global/cscratch1/sd/llei2019/B_hybridum/Ruben_synteny/scripts/VcftoHamapVariscan_conditionArg-AncestralAllele.pl /global/u2/l/llei2019/cscratch/B_hybridum/Ruben_synteny/fake_parents_ref_way/fix_header_revised_purify_Bstacei.recode.vcf  /global/u2/l/llei2019/cscratch/B_hybridum/Ruben_synteny/fake_parents_ref_way/fix_header_revised_purify_Bstacei 0

